### ISSUE TITLE
Usage of the field "shortlink" ?

### ISSUE THREAD

**Issue by jhice** [bobdenotter/seo#20]
Hi,

Trying to get to the "shortlink" field working, and it seems not to be used anywhere in the source code. For example :

/pages/my-shortlink-url
or
/my-shortlink-url
return a 404 (no route found).

How can we use it ?
Thanks

**Comment by annejan** [comment]
I have the same issue.

Any help would be appreciated @bobdenotter

**Comment by bobdenotter** [comment]
This feature wasn't implemented I think. One of those things i figured would be handy to have, but I never got around to implementing it yet. 

If somebody would like to help out on implementing it, that'd be great. :-)

**Comment by annejan** [comment]
Currently looking into how https://github.com/AnimalDesign/bolt-shorturl does it . .
They seem to work well together too . . adding the shorturl behind the seo in my `contenttypes.yml`

```
        seo:
            type: seo
            group: "SEO settings"
        shorturl:
            type: shorturl
```

Adds the shorturl box inside the SEO tab . .
