### ISSUE TITLE
Field type error.

### ISSUE THREAD

**Issue by jnn-tlr** [bobdenotter/seo#26]
Hello,

I installed the extension and I'm having trouble getting it to work with my contenttype. I added the specified field name and type, but after saving I get the following notice: "In the contenttype for 'Home', the field 'seo' has 'type: seo', which is not a proper field type. Please edit contenttypes.yml, and correct this. "

Any help would be appreciated.

**Comment by jasperjorna** [comment]
Can you post your `contenttypes.yml`?

**Comment by jnn-tlr** [comment]
See below. The seo field is at the very bottom.

```
member:
    name: Member
    singular_name: Member
    viewless: true
    fields:
        first_name:
            type: text
            label: First Name
            group: Info
        last_name:
            type: text
            label: Last Name
        company:
            type: text
            label: Company
        address:
            type: text
        suite_number:
            type: text
            label: Suite / Apt #
        city:
            type: text
        state:
            type: select
            values: [AL,AK,AZ,AR,CA,CO,CT,DE,FL,GA,HI,ID,IL,IN,IA,KS,KY,LA,ME,MD,MA,MI,MN,MS,MO,MT,NS,NV,NH,NJ,NM,NY,NC,ND,OH,OK,OR,PA,RI,SC,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY]
        zipcode:
            type: text
            label: Zip Code
        phone:
            type: text
            label: Phone Number
        email:
            type: text
            label: E-Mail
        team_name:
            type: text
            label: Team Name
            group: Team
        team_two_name:
            type: text
            label: Team Two Name
            group: Team
        teamplayer:
            type: repeater
            label: Team Player
            group: Team Players 1
            fields:
                name:
                    label: Name
                    type: text
                mail:
                    type: text
                    label: Mail
                phone:
                    type: text
                    label: Phone
                veteran:
                    type: checkbox
                    label: Is Veteran
                rentgolf:
                    type: checkbox
                    label: Rent Golf Club
        teamplayertwo:
            type: repeater
            label: Team Player
            group: Team Players 2
            fields:
                name:
                    label: Name
                    type: text
                mail:
                    type: text
                    label: Mail
                phone:
                    type: text
                    label: Phone
                veteran:
                    type: checkbox
                    label: Is Veteran
                rentgolf:
                    type: checkbox
                    label: Rent Golf Club
        extraattendees:
            type: repeater
            group: Extra Attendees
            prefix: "<p>Extra Attendees</p>"
            fields:
                name:
                    type: text
        paymenttype:
            type: select
            label: Payment Type
            values: [CHECK, CARD]
            group: Payment
        paymentstatus:
            type: select
            label: Payment Status
            values: [PENDING, PAYED]
        stripeid:
            type: text
            label: Stripe ID
    relations:
        sponsortype:
            label: Sponsor Type
            multiple: true
        hole:
            label: Holes
            multiple: true

sponsortype:
    name: Sponsor Types
    singular_name: Sponsor Type
    fields:
        name:
            type: text
            group: Info
        available:
            type: integer
            label: Avail Number
        fieldtype:
            type: select
            values: [CHECKBOX, RADIO]
            label: Field Type
        fieldgroup:
            type: text
            label: Field Group
        fieldname:
            type: text
            label: Field Name
        fieldautoactivate:
            type: checkbox
            label: Field Auto Activate when player hit
        fieldmaximumplayer:
            type: integer
            label: Field Maximum Player
        fieldminimumplayer:
            type: integer
            label: Field Minimum Player
        fieldcalculatebyplayer:
            type: checkbox
            label: Field Calculate By Player
        price:
            type: float
        sponsorholes:
            label: Sponsor Holes
            type: checkbox
        maximumholesponsor:
            label: Maximum Holes to Sponsor
            type: integer
        requireextranames:
            label: Require Extra Names
            type: checkbox
        requireextrateam:
            label: Require Extra Team
            type: checkbox
        description:
            label: Description
            type: html

hole:
    name: Holes
    singular_name: Hole
    viewless: false
    fields:
        title:
            type: text
        holestatus:
            type: select
            values: [AVAIL, TAKEN]
    relations:
        member:
            label: Hole Member
            multiple: false

schedule:
    name: Schedule
    singular_name: Schedule
    viewless: false
    fields:
        title:
            type: text
        hours:
            type: text
        descriptiontitle:
            type: text
            label: Description Title
        description:
            type: html
        ordernum:
            type: integer
            label: Order Number

sponsors:
    name: Sponsors
    singular_name: Sponsor
    viewless: false
    fields:
        name:
            type: text
        image:
            type: image
        sponsorurl:
            type: text
            label: Sponsor Website Link

faq:
    name: FAQ
    singular_name: FAQ
    viewless: false
    fields:
        question:
            type: text
        answer:
            type: textarea           

home:
    name: Home
    singular_name: Home
    record_template: index.twig
    fields:
        main_title:
            type: text
            label: Main Title
            group: Top Block
        sub_title:
            type: text
            label: Sub Title
        column1_text:
            type: textarea
            label: Column 1 Text
        column2_text:
            type: textarea
            label: Column 2 Text
        register_text:
            type: html
            label: Register Text

        about_event:
            type: html
            label: About Our Event
            group: About Our Event Block
        numbers:
            type: repeater
            limit: 6
            prefix: "<p>These are the right block numbers</p>"
            fields:
                number:
                    type: integer
                description:
                    type: text
        video:
            type: video
            group: Video Block
        video_title:
            type: text
            label: Video Title
        video_text:
            type: textarea
            label: Video Text
        event_time:
            type: datetime
            label: Event Date and Time
            group: Countdown Block
        event_address:
            type: geolocation
            label: Address
            group: Address Block
        event_contact:
            type: text
            label: Contact Number
        event_mail:
            type: text
            label: Contact E-Mail
            pattern: email
        social:
            type: repeater
            limit: 5
            prefix: "<p>Use this to add social media icons</p>"
            fields:
                icon:
                    type: text
                    prefix: "<p>Insert a FontAwesome icon class</p>"
                link:
                    type: text                       
        seo:
            type: seo
            group: "SEO settings"
```
