### ISSUE TITLE
[RFC] Add ability for custom meta tag logic

### ISSUE THREAD

**Issue by Pinpickle** [bobdenotter/seo#3]
I currently generate my meta tags manually with some twig logic, and for the most part it is similar to the logic in this extension, but every project does things slightly differently.

I don't know how this would be implemented, but it would be great if we could somehow provide our own ways of specifying meta tag values in the "fallback chain" of logic in this extension. For example, I may want the title to be the combination of two different fields, if they're filled, and then fall back to what the extension specifies.

**Comment by jasperjorna** [comment]
Correct me if I'm wrong. Could this be achieved by simple overriding the template in the themes directory?

Currently it seems the path is prefixed though?

https://github.com/bobdenotter/seo/blob/master/Extension.php#L38

**Comment by bobdenotter** [comment]
I'm also not sure how to configure this.. Maybe allow for a 'general' seo title option, and the possibility to override them on a per-contenttype basis? 

or, perhaps allow to override the title in the contenttypes.yml setting? 

```
    fields:
        [..]
        seo:
            type: seo
            group: "SEO settings"
            title: [ name, subtitle ]
```
