### ISSUE TITLE
[FEATURE] Add option to override OG:image

### ISSUE THREAD

**Issue by sbonardt** [bobdenotter/seo#40]
I would like to be able to specify a default image to use for the OG image tag coming from the content type. So the user can upload a specifi one if needed, and the code fall back to defaults if it isn't present. Could you add it to the config? That would be nice.

like for when i have a conten type with a field "ogimage", in the config for the SEO extension I would set:

```
# Default values to consider for the title, meta description and meta keywords
fields:
    title: ['title', 'name']
    description: ['introduction', 'teaser', 'description', 'body']
    keywords: []
    image: ['ogimage']
```

thanks
