### ISSUE TITLE
can't figure out how to disable properly shortlink, canonical and robots

### ISSUE THREAD

**Issue by jeremyriverain** [bobdenotter/seo#48]
I tried to enable shortink, canonical and robots just for the admin.

In app/config/extensions/seo.bodenotter.yml, the default proposition is:
```
allow:
    shortlink: [chief-editor, admin, developper, root]
    canonical: [chief-editor, admin, developper, root]
    robots: [chief-editor, admin, developper, root]
```
I uncommented these lines modifying it like this:
```
allow:
    shortlink: [admin]
    canonical: [admin]
    robots: [admin]
```
But it doesn't work. 

In vendor/bobdenotter/seo/templates/_seoextension_field.twig, I noticed lines 109, 123, 137 that the variables are set to `seoconfig.allowed.options|default(true)`

The only way I succeeded to disable canonical, robots and shortlink was to hardcode this file, deleting the default option, resulting in `seoconfig.allowed.options` instead of `seoconfig.allowed.options|default(true)` for each lines cited above.

And modifying my seo.bodenotter.yml, I did that:
```
allowed:
    shortlink: false
    canonical: false
    robots: false
```
It effectively disabled these 3 options but as I'm not a fan about hardcoding a vendor file because of the possible override after an update, I want to know if there is a better way to do that. And how is it possible to enable these options just for the admin?

Thanks for your patience and I apologize in advance if my English is incorrect, hoping you guess the meaning of my question.
