### ISSUE TITLE
Set Title and Description for listing page

### ISSUE THREAD

**Issue by dadaxr** [bobdenotter/seo#6]
I have a url which looks like : http://mysite.com/blog 
which is an alias of http://mysite.com/entries ( the content type listing )
and I should be able to set a custom title and description metas for that explicit page.

Maybe add an override array based on the "page" slug in the extension config file ? Or a check on a global twig variable which could be overrided in a template ?

**Comment by bobdenotter** [comment]
Hi, 

I'm assuming you're using listing pages as `/category/movies', right? In this case it is't tied to a specifiv record, and the extension won't know how to create a title and excerpt for it.. 

How about we add these to the config for the extension:

```
contenttypes: 
    pages: 
        title: "Title for pages" 
        Description: "Meta description for pages. Meta description for pages. Meta description for pages." 
    entries: 
        title: "Title for entries" 
        Description: "Meta description for entries. Meta description for pages. Meta description for entries." 
```

Would that work?
