### ISSUE TITLE
Feature request : default fallback image

### ISSUE THREAD

**Issue by ankedsgn** [bobdenotter/seo#67]
Wishlist!
It would be lovely if there would be a default image possibility. So you can, for instance, add the logo of the company in the OG tags when no image is present in the shared page.

The og:image is one of the four required properties (title, type, url and image) [sauce](http://ogp.me/#metadata)

```
default:
    title: ""
    description: ""
    ogtype: "website" 
    image: "foo.jpg"
```

preferably like this, in the config.

Thx!

-----
used version: 1.0.7
